name: Run Tests

on:
  pull_request:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go 1.23.x
        uses: actions/setup-go@v5
        with:
          # Semantic version range syntax or exact version of Go
          go-version: '1.23.x'
          cache-dependency-path: subdir/go.sum

      - name: Set GOFLAGS to use vendor directory 
        run: echo "GOFLAGS=-mod=vendor" >> $GITHUB_ENV

      - name: Install tools
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          go install github.com/securego/gosec/v2/cmd/gosec@latest
          go install gotest.tools/gotestsum@latest

      - name: Install Dependencies
        run: go mod tidy && go mod vendor

      - name: Run Formatting Check
        run: test -z $(go fmt ./...)

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Pull Docker image
        run: docker pull manifoldlabs/subtensor:fast-blocks

      - name: Configure Testcontainers
        run: |
          echo "TESTCONTAINERS_RYUK_DISABLED=true" >> $GITHUB_ENV
          echo "DOCKER_HOST=unix:///var/run/docker.sock" >> $GITHUB_ENV

      - name: Run Linting 
        run: staticcheck ./...

      - name: Run Security Check
        run: gosec ./...

      - name: Test Extrinsics
        run: gotestsum --format testname -- -v -p 10 -tags=integration ./...



        
